apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/git-ly/catalog-service/k8s?ref=main

patchesStrategicMerge:
  - patch-env.yml
  - patch-resources.yml
  - path-volumes.yml

configMapGenerator:
  - behavior: merge
    files:
      - application-prod.yml
    name: catalog-config

images:
  - name: catalog-service
    newName: ghcr.io/git-ly/catalog-service
    newTag: latest

replicas:
  - count: 2
    name: catalog-service